# Generated by Django 4.2.6 on 2023-10-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0004_menbros'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbros',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cpre.pais'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('duracao', models.TimeField()),
                ('classificacao', models.IntegerField()),
                ('Produtora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpre.produtora')),
            ],
        ),
    ]
