# Generated by Django 4.2.6 on 2023-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0005_menbros_pais_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='Categoria',
            field=models.ManyToManyField(to='cpre.categoria'),
        ),
    ]
