# Generated by Django 4.2.6 on 2023-10-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0006_filme_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoatuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Menbros',
            new_name='Membros',
        ),
        migrations.RemoveField(
            model_name='atuacao',
            name='descricao',
        ),
        migrations.AddField(
            model_name='atuacao',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cpre.filme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atuacao',
            name='membro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cpre.membros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atuacao',
            name='personagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atuacao',
            name='tipoatuacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cpre.tipoatuacao'),
            preserve_default=False,
        ),
    ]
