# Generated by Django 5.0 on 2023-12-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0007_tipoatuacao_rename_menbros_membros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='Produtora',
        ),
        migrations.RemoveField(
            model_name='membros',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='produtora',
            name='pais',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpre.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='atuacao',
        ),
        migrations.DeleteModel(
            name='tipoatuacao',
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Membros',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Produtora',
        ),
    ]
