# Generated by Django 5.0 on 2023-12-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0008_remove_filme_categoria_remove_filme_produtora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
