# Generated by Django 5.0 on 2023-12-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0009_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
