# Generated by Django 5.0 on 2023-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0010_alter_categoria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
