# Generated by Django 5.0 on 2023-12-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpre', '0011_categorias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
